name: lazx_idea
description: A starter app project for Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.3
  meta: ^1.7.0
  flutter_svg: ^2.0.4
  url_launcher: ^6.1.10
  intl: ^0.17.0
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.9.3
  shared_preferences: ^2.0.18
  lazx:
    path: ../../
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  mockito: ^5.2.0

flutter:

  uses-material-design: true
#  assets:
#    - assets/img/
#    - assets/svg/
#    - assets/icon/
#    - .env

#  fonts:
#    - family: BigJohn
#      fonts:
#        - asset: fonts/BigJohnPRO-Regular.otf
#    - family: BigJohn-Light
#      fonts:
#        - asset: fonts/BigJohnPRO-Light.otf
#    - family: BigJohn-Bold
#      fonts:
#        - asset: fonts/BigJohnPRO-Bold.otf
