name: lazx
description: A state management library based on the ViewModel design pattern for Flutter.
version: 1.0.1
homepage: https://github.com/borombo-git/lazx

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.1
  provider: ^5.0.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  test: ^1.16.0

flutter:

