name: lazx_weather
description: Weahter app using Lazx

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.3
  meta: ^1.11.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  auto_size_text: ^3.0.0
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  dio: ^5.5.0+1
  rxdart: ^0.28.0
  intl: ^0.19.0
  lazx:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/svg/
    - .env

  fonts:
    - family: AvenirNext
      fonts:
        - asset: fonts/AvenirNext-Regular.ttf
    - family: AvenirNext-Bold
      fonts:
        - asset: fonts/AvenirNext-Bold.ttf
    - family: AvenirNext-Heavy
      fonts:
        - asset: fonts/AvenirNext-Heavy.ttf