# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get
        
      - name: Install Lazx Weather dependencies
        working-directory: ./demos/lazx-weather
        run: flutter pub get
        
      - name: Install Lazx Ideas dependencies
        working-directory: ./demos/lazx-ideas
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test --coverage
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
